import {z} from "zod";
import {api,jsonBody,response} from "@/lib/api/http";
import {apiContext,audit} from "@/lib/api/context";
import {db} from "@/lib/db";
import {ApiError} from "@/lib/api/errors";
const create=z.object({title:z.string().trim().min(1).max(200),body:z.string().max(2000).default(''),caseId:z.string().uuid().optional(),dueAt:z.string().datetime({offset:true}),repeatFrequency:z.enum(['NONE','DAILY','WEEKLY']).default('NONE'),priority:z.enum(['LOW','MEDIUM','HIGH','CRITICAL']).default('MEDIUM')}).strict();
export const GET=api(async request=>{const c=await apiContext(request);return response(await db().query('select id,title,body,case_id as "caseId",due_at as "dueAt",repeat_frequency as "repeatFrequency",priority,status from reminders where tenant_id=$1 and user_id=$2 order by status,due_at limit 200',[c.tenantId,c.actorId]));});
export const POST=api(async request=>{const c=await apiContext(request),input=await jsonBody(request,create);if(Date.parse(input.dueAt)<=Date.now())throw new ApiError(422,'REMINDER_IN_PAST','Elegí una fecha futura para el recordatorio.');if(input.caseId&&!(await db().query('select id from cases where tenant_id=$1 and id=$2 and deleted_at is null',[c.tenantId,input.caseId])).length)throw new ApiError(404,'NOT_FOUND','La causa no es accesible.');const rows=await db().query('insert into reminders(tenant_id,user_id,case_id,title,body,due_at,repeat_frequency,priority,created_by) values($1,$2,$3,$4,$5,$6,$7,$8,$2) returning id',[c.tenantId,c.actorId,input.caseId??null,input.title,input.body,input.dueAt,input.repeatFrequency,input.priority]);await audit(c,'REMINDER_CREATED','reminder',rows[0]!.id,{dueAt:input.dueAt,repeatFrequency:input.repeatFrequency});return response(rows[0],{status:201});});
export const PATCH=api(async request=>{const c=await apiContext(request),input=await jsonBody(request,z.object({id:z.string().uuid(),status:z.enum(['CANCELLED','COMPLETED','ACTIVE']),dueAt:z.string().datetime({offset:true}).optional()}).strict());if(input.status==='ACTIVE'&&(!input.dueAt||Date.parse(input.dueAt)<=Date.now()))throw new ApiError(422,'REMINDER_DATE_REQUIRED','Indicá una nueva fecha futura.');const rows=await db().query('update reminders set status=$3,due_at=coalesce($4::timestamptz,due_at) where tenant_id=$1 and user_id=$2 and id=$5 returning id',[c.tenantId,c.actorId,input.status,input.dueAt??null,input.id]);if(!rows.length)throw new ApiError(404,'NOT_FOUND','El recordatorio no existe.');await audit(c,'REMINDER_UPDATED','reminder',input.id,{status:input.status});return response(rows[0]);});
