import fs from 'node:fs';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {neon} from '@neondatabase/serverless';
const env=Object.fromEntries(fs.readFileSync('apps/web/.env.local','utf8').split('\n').filter(x=>x.includes('=')).map(x=>[x.slice(0,x.indexOf('=')),x.slice(x.indexOf('=')+1)]));if(env.MONITOR_LEGAL_VALIDATION!=='true')throw new Error('Use isolated validation branch');const sql=neon(env.DATABASE_AUTH_URL),scheduler=neon(env.DATABASE_SCHEDULER_URL),{cookie}=JSON.parse(fs.readFileSync('/tmp/monitor-legal-validation-session.json','utf8')),key=env.ALERT_CRON_KEY,report=[];
async function req(path,body,method=body?'POST':'GET',credential=cookie){const r=await fetch('http://localhost:3000'+path,{method,headers:{Origin:'http://localhost:3000','Content-Type':'application/json',Cookie:credential},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,json:await r.json()};}
function check(name,v){assert.ok(v,name);report.push(name);console.log('PASS',name);}
async function tick(){const r=await fetch('http://localhost:3000/api/internal/reminders',{method:'POST',headers:{Authorization:'Bearer '+key}});const j=await r.json();check('Scheduler tick succeeds',r.status===200);return j;}
const me=await req('/api/me');check('Synthetic owner session',me.status===200);const c=me.json.data;
const next=new Date(Date.now()+86400000).toISOString(),created=await req('/api/reminders',{title:'SYNTHETIC daily reminder',dueAt:next,repeatFrequency:'DAILY',priority:'HIGH'});check('Personal repeating reminder creation',created.status===201);const id=created.json.data.id;
await sql.query('update reminders set due_at=now()-interval \'1 minute\' where id=$1',[id]);await tick();let notices=await sql.query("select count(*)::int n from notifications where tenant_id=$1 and user_id=$2 and idempotency_key like $3",[c.tenantId,c.actorId,'reminder:'+id+':%']);check('Due reminder becomes persistent alert',notices[0].n===1);await tick();notices=await sql.query("select count(*)::int n from notifications where tenant_id=$1 and user_id=$2 and idempotency_key like $3",[c.tenantId,c.actorId,'reminder:'+id+':%']);check('Repeated ticks do not duplicate an alert',notices[0].n===1);const [repeat]=await sql.query('select status,due_at>now() as future from reminders where id=$1',[id]);check('Daily recurrence advances to future',repeat.status==='ACTIVE'&&repeat.future);
const alerts=await req('/api/alerts?unread=true');check('Dashboard lists actual alerts',alerts.status===200&&alerts.json.data.some(a=>a.title==='SYNTHETIC daily reminder'));
const alert=alerts.json.data.find(a=>a.title==='SYNTHETIC daily reminder');const snoozed=await req('/api/alerts',{id:alert.id,action:'SNOOZE',snoozedUntil:new Date(Date.now()+3600000).toISOString()},'PATCH');check('Alert snooze works',snoozed.status===200);const hidden=await req('/api/alerts?unread=true');check('Snoozed alert leaves unread badge',!hidden.json.data.some(a=>a.id===alert.id));check('Mark alert read',(await req('/api/alerts',{id:alert.id,action:'READ'},'PATCH')).status===200);
const h=Number(new Intl.DateTimeFormat('en-GB',{hour:'2-digit',hour12:false,timeZone:'America/Argentina/Buenos_Aires'}).format(new Date()));await req('/api/alert-settings',{enabledKinds:['DEADLINE'],quietStart:h,quietEnd:(h+1)%24},'PUT');const quiet=await req('/api/reminders',{title:'SYNTHETIC quiet reminder',dueAt:next});await sql.query("update reminders set due_at=now()-interval '1 minute' where id=$1",[quiet.json.data.id]);await tick();let q=await sql.query('select status from reminders where id=$1',[quiet.json.data.id]);check('Quiet hours postpone delivery',q[0].status==='ACTIVE');await req('/api/alert-settings',{enabledKinds:Object.keys({DEADLINE:1,TASK:1,EVENT:1,AGENDA:1,CLIENT:1,LEAD:1,CONNECTOR:1,DOCUMENT:1}),quietStart:null,quietEnd:null},'PUT');await tick();q=await sql.query('select status from reminders where id=$1',[quiet.json.data.id]);check('Delivery resumes after quiet hours',q[0].status==='COMPLETED');
const cases=await req('/api/cases');const caseId=cases.json.data[0].id;
const deadline=await req('/api/deadlines',{caseId,title:'SYNTHETIC possible deadline',dueAt:new Date(Date.now()+3600000).toISOString(),status:'POSSIBLE'});check('Recorded possible deadline created',deadline.status===201);await tick();const [d]=await sql.query('select status from deadlines where id=$1',[deadline.json.data.id]);check('Alerts never auto-confirm procedural deadlines',d.status==='POSSIBLE');const deadlineAlerts=await req('/api/alerts');check('Possible deadline is clearly labeled',deadlineAlerts.json.data.some(a=>a.kind==='DEADLINE'&&a.title.includes('pendiente de confirmar')));
let denied=false;try{await scheduler.query('select * from cases limit 1');}catch(e){denied=e.code==='42501';}check('Scheduler role cannot read business tables',denied);
check('Scheduler endpoint requires private key',(await fetch('http://localhost:3000/api/internal/reminders',{method:'POST'})).status===401);
const nlp=await req('/api/agent',{message:`Creá un recordatorio personal sin causa para revisar mis pendientes el ${next}. Título: SYNTHETIC recordatorio del asistente. Quiero una propuesta para aprobar.`,mode:'operations'});check('Agent understands natural reminder request',nlp.status===200);const state=await req('/api/agent');const proposal=state.json.data.approvals.find(a=>a.action==='CREATE_REMINDER');check('Agent proposes a reminder pending approval',!!proposal);const approval=await req('/api/agent/approvals/'+proposal.id,{decision:'APPROVE'});check('Approving agent reminder programs it',approval.status===200&&approval.json.data.resultId);const duplicate=await req('/api/agent/approvals/'+proposal.id,{decision:'APPROVE'});check('Reminder approval cannot replay',duplicate.status===409);
const badPush=await req('/api/push',{endpoint:'https://127.0.0.1/private',keys:{p256dh:'x'.repeat(60),auth:'x'.repeat(24)}});check('Push rejects arbitrary network endpoints',badPush.status===422||badPush.status===400);
check('Reminder cancellation',(await req('/api/reminders',{id,status:'CANCELLED'},'PATCH')).status===200);
fs.writeFileSync('/tmp/monitor-reminders-report.json',JSON.stringify(report,null,2));console.log('Verified',report.length,'reminder and alert checks');
