import type { TodayDashboard } from "@/lib/dashboard";

export const demoDashboard: TodayDashboard = {
  actorName: "Tobias",
  dateLabel: "Lunes 27 de julio",
  summary: {
    urgent: 2,
    possibleDeadlines: 3,
    overdueTasks: 1,
    upcoming: 4,
    notifications: 5,
    waitingClients: 3,
    untouchedLeads: 2,
    syncFailures: 1,
  },
  attention: [
    {
      id: "event-1",
      type: "EVENT",
      title: "Posible traslado detectado",
      context: "Pérez Ejemplo c/ Empresa Demo S.A.",
      source: "PJN",
      relativeTime: "hace 24 min",
      reason: "Contiene términos asociados a traslado. Requiere revisión profesional.",
      owner: "Tobias Gatti",
      priority: "CRITICAL",
      primaryAction: "Revisar",
    },
    {
      id: "deadline-1",
      type: "DEADLINE",
      title: "Fecha detectada sin confirmar",
      context: "Incidente FCR 42/2026",
      source: "PJN",
      relativeTime: "hace 1 h",
      reason: "Se detectó una fecha a 48 horas; aún no es un plazo confirmado.",
      owner: "Sin asignar",
      priority: "HIGH",
      primaryAction: "Confirmar fecha",
    },
    {
      id: "sync-1",
      type: "SYNC",
      title: "SCBA requiere conexión local",
      context: "Integración Notificaciones Electrónicas",
      source: "SCBA",
      relativeTime: "hace 2 h",
      reason: "El agente local no reportó estado. PJN continúa funcionando.",
      owner: "Administración",
      priority: "HIGH",
      primaryAction: "Ver diagnóstico",
    },
    {
      id: "communication-1",
      type: "COMMUNICATION",
      title: "Cliente espera una actualización",
      context: "María Ejemplo · Daños y perjuicios",
      source: "ESTUDIO",
      relativeTime: "hace 3 días",
      reason: "Hay una novedad revisada que todavía no fue comunicada.",
      owner: "Tobias Gatti",
      priority: "MEDIUM",
      primaryAction: "Redactar mensaje",
    },
  ],
  agenda: [
    {
      id: "agenda-1",
      time: "09:30",
      title: "Revisar cédula recibida",
      context: "FCR 42/2026 · Posible plazo",
      kind: "DEADLINE",
      completed: false,
    },
    {
      id: "agenda-2",
      time: "11:00",
      title: "Reunión con cliente",
      context: "María Ejemplo · videollamada",
      kind: "MEETING",
      completed: false,
    },
    {
      id: "agenda-3",
      time: "14:00",
      title: "Preparar documental",
      context: "Gómez Ejemplo c/ Aseguradora Demo",
      kind: "TASK",
      completed: false,
    },
    {
      id: "agenda-4",
      time: "17:30",
      title: "Seguimiento de propuesta",
      context: "Lead · Consulta laboral",
      kind: "FOLLOW_UP",
      completed: true,
    },
  ],
  communications: [
    {
      id: "client-1",
      client: "María Ejemplo",
      matter: "Daños y perjuicios",
      reason: "Novedad revisada sin comunicar",
      daysWaiting: 3,
      whatsapp: "5492915550101",
      email: "maria@example.com",
    },
    {
      id: "client-2",
      client: "Comercial Demo S.A.",
      matter: "Cobro contractual",
      reason: "Contacto prometido para hoy",
      daysWaiting: 1,
      whatsapp: "5492915550102",
      email: "legal@example.com",
    },
    {
      id: "client-3",
      client: "Juan Ficticio",
      matter: "Reclamo administrativo",
      reason: "Consulta pendiente de respuesta",
      daysWaiting: 2,
      whatsapp: null,
      email: "juan@example.com",
    },
  ],
  leads: [
    {
      id: "lead-1",
      name: "Sofía Prueba",
      matter: "Consulta laboral",
      stage: "Nuevo",
      nextAction: "Primera respuesta",
      overdue: true,
    },
    {
      id: "lead-2",
      name: "Empresa Ficticia SRL",
      matter: "Conflicto societario",
      stage: "Propuesta enviada",
      nextAction: "Seguimiento hoy 16:00",
      overdue: false,
    },
  ],
  integrations: [
    {
      id: "pjn",
      name: "PJN · Gatti",
      status: "HEALTHY",
      lastSync: "18:24",
      detail: "26 causas revisadas",
    },
    {
      id: "pjn-2",
      name: "PJN · Mazzarini",
      status: "HEALTHY",
      lastSync: "18:24",
      detail: "Sin novedades",
    },
    {
      id: "mev",
      name: "MEV SCBA",
      status: "NOT_CONFIGURED",
      lastSync: "Nunca",
      detail: "Se habilitará después de estabilizar PJN",
    },
    {
      id: "scba",
      name: "SCBA Notificaciones",
      status: "OFFLINE",
      lastSync: "16:08",
      detail: "Agente local desconectado",
    },
  ],
};
